
module.exports = {
	GO_TO_SCREEN: "GO_TO_SCREEN",

	USER_LOGGED_IN: "USER_LOGGED_IN",

	GO_TO_SHARE_POST_STEP_1: "GO_TO_SHARE_POST_STEP_1",
	GO_TO_SHARE_POST_STEP_2: "GO_TO_SHARE_POST_STEP_2",
	SHARE_POST: "SHARE_POST",
	CANCEL_SHARE_POST: "CANCEL_SHARE_POST",
	PENDING_POST_APPROVED: "PENDING_POST_APPROVED",

	NEW_POSTS: "NEW_POSTS",

	SET_LOCATION: "SET_LOCATION"
};